### ISSUE TITLE
Can it support dual screen display?

### ISSUE THREAD

**Issue by dengshenkk** [linhnguyengas/Hackintosh-Desktop-Msi-H110M-PRO-VD-PLUS#1]
Can VGA and DVI support dual display? Or DVI to HDMI

**Comment by linhnguyengas** [comment]
> Can VGA and DVI support dual display? Or DVI to HDMI

MacOS not support VGA,my knowledge MacOS just support DVI and HDMI, but I have not try yet DVI display :)

**Comment by dengshenkk** [comment]
@linhnguyengas get it.  Anyway,  DVI to HDMI is worked!!
